spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
