spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/realm
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
