spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
             - name: RequestRateLimiter
               args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: inventory
          uri: lb://=inventory
          predicates:
            - Path=/=inventory/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*'
